### ISSUE TITLE
container-diff does not support "digest"

### ISSUE THREAD

**Issue by kenotsolutions** [GoogleContainerTools/container-diff#353] opened 2021-02-25 19:20 UTC
Hi,

Container_diff analyse or check the differences between two images from the tag name but sometimes we may need to check the differences between the two digest versions.

container-diff analyze ubuntu@sha256:45b23dee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c5cb2

RRO[0002] error retrieving image ubuntu@sha256:45b23dee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c5cb2

### Expected behavior
container-diff analyze ubuntu@sha256:45b23dee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c5cb2

-----Size-----

Analysis for ubuntu:
IMAGE         DIGEST                                                                         SIZE
ubuntu        sha256:45b23dee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c5cb2        72.9M

**Comment by MPV** [comment] 2023-12-14 11:06
Am I getting the same issue here?

```
$ container-diff diff \
	hashicorp/envconsul:0.13.1@sha256:b10b19cb5a1d492f9b456733f9ab23eac177d24851bda9917ece8f6a0ab34429 \
	hashicorp/envconsul:0.13.1@sha256:33b18061f00c30e6f1e55f298cee9638b1a5c2f08554172207ddb00a44157122
ERRO[0000] error retrieving image hashicorp/envconsul:0.13.1@sha256:33b18061f00c30e6f1e55f298cee9638b1a5c2f08554172207ddb00a44157122: parsing image reference: could not parse reference
error retrieving image hashicorp/envconsul:0.13.1@sha256:b10b19cb5a1d492f9b456733f9ab23eac177d24851bda9917ece8f6a0ab34429: parsing image reference: could not parse reference
```

**Comment by MPV** [comment] 2023-12-14 11:07
Also, is this a duplicate of...?
- https://github.com/GoogleContainerTools/container-diff/issues/353

**Closed** 2024-03-27 18:01 UTC
